name: UndergroundVillageBuilder
main: com.eatsleepcode.undergroundvillagebuilder.UndergroundVillageBuilder
version: 2025.02.15.09
api: [1.0.11]
author: eat-sleep-code
description: Build a complex underground village.
commands:
  undergroundvillage:
    description: Build a complex underground village.
    usage: /undergroundvillage <depth>
    permission: undergroundvillage.create
